In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report

In [2]:
df = pd.read_csv('nasa.csv')

In [3]:
df.head()

   Neo Reference ID     Name  ...  Equinox  Hazardous
0           3703080  3703080  ...    J2000       True
1           3723955  3723955  ...    J2000      False
2           2446862  2446862  ...    J2000       True
3           3092506  3092506  ...    J2000      False
4           3514799  3514799  ...    J2000       True

[5 rows x 40 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4687 entries, 0 to 4686
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Neo Reference ID              4687 non-null   int64
 1   Name                          4687 non-null   int64
 2   Absolute Magnitude            4687 non-null   float64
 3   Est Dia in KM(min)            4687 non-null   float64
 4   Est Dia in KM(max)            4687 non-null   float64
 5   Est Dia in M(min)             4687 non-null   float64
 6   Est Dia in M(max)             4687 non-null   float64
 7   Est Dia in Miles(min)         4687 non-null   float64
 8   Est Dia in Miles(max)         4687 non-null   float64
 9   Est Dia in Feet(min)          4687 non-null   float64
 10  Est Dia in Feet(max)          4687 non-null   float64
 11  Close Approach Date           4687 non-null   object
 12  Epoch Date Close Approach     4687 non-null   int64
 13  Relative Velocity km per sec  4687 non-null   float64
 14  Relative Velocity km per hr   4687 non-null   float64
 15  Miles per hour                4687 non-null   float64
 16  Miss Dist.(Astronomical)      4687 non-null   float64
 17  Miss Dist.(lunar)             4687 non-null   float64
 18  Miss Dist.(kilometers)        4687 non-null   float64
 19  Miss Dist.(miles)             4687 non-null   float64
 20  Orbiting Body                 4687 non-null   object
 21  Orbit ID                      4687 non-null   int64
 22  Orbit Determination Date      4687 non-null   object
 23  Orbit Uncertainity            4687 non-null   int64
 24  Minimum Orbit Intersection    4687 non-null   float64
 25  Jupiter Tisserand Invariant   4687 non-null   float64
 26  Epoch Osculation              4687 non-null   float64
 27  Eccentricity                  4687 non-null   float64
 28  Semi Major Axis               4687 non-null   float64
 29  Inclination                   4687 non-null   float64
 30  Asc Node Longitude            4687 non-null   float64
 31  Orbital Period                4687 non-null   float64
 32  Perihelion Distance           4687 non-null   float64
 33  Perihelion Arg                4687 non-null   float64
 34  Aphelion Dist                 4687 non-null   float64
 35  Perihelion Time               4687 non-null   float64
 36  Mean Anomaly                  4687 non-null   float64
 37  Mean Motion                   4687 non-null   float64
 38  Equinox                       4687 non-null   object
 39  Hazardous                     4687 non-null   bool
dtypes: bool(1), float64(30), int64(5), object(4)
memory usage: 1.4+ MB

In [5]:
df.describe()

       Neo Reference ID          Name  ...  Mean Anomaly  Mean Motion
count      4.687000e+03  4.687000e+03  ...   4687.000000  4687.000000
mean       3.272298e+06  3.272298e+06  ...    181.167927     0.738242
std        5.486011e+05  5.486011e+05  ...    107.501623     0.342627
min        2.000433e+06  2.000433e+06  ...      0.003191     0.086285
25%        3.097594e+06  3.097594e+06  ...     87.006918     0.453289
50%        3.514799e+06  3.514799e+06  ...    185.718889     0.712946
75%        3.690060e+06  3.690060e+06  ...    276.531946     0.984669
max        3.781897e+06  3.781897e+06  ...    359.917991     2.039000

[8 rows x 35 columns]

In [6]:
df.shape

(4687, 40)

In [7]:
#Remove unwanted
df.drop(['Neo Reference ID','Name','Close Approach Date','Equinox','Orbiting Body','Orbit Determination Date'],axis=1,inplace=True)

In [8]:
df.isnull().sum()

Absolute Magnitude              0
Est Dia in KM(min)              0
Est Dia in KM(max)              0
Est Dia in M(min)               0
Est Dia in M(max)               0
Est Dia in Miles(min)           0
Est Dia in Miles(max)           0
Est Dia in Feet(min)            0
Est Dia in Feet(max)            0
Epoch Date Close Approach       0
Relative Velocity km per sec    0
Relative Velocity km per hr     0
Miles per hour                  0
Miss Dist.(Astronomical)        0
Miss Dist.(lunar)               0
Miss Dist.(kilometers)          0
Miss Dist.(miles)               0
Orbit ID                        0
Orbit Uncertainity              0
Minimum Orbit Intersection      0
Jupiter Tisserand Invariant     0
Epoch Osculation                0
Eccentricity                    0
Semi Major Axis                 0
Inclination                     0
Asc Node Longitude              0
Orbital Period                  0
Perihelion Distance             0
Perihelion Arg                  0
Aphelion Dist                   0
Perihelion Time                 0
Mean Anomaly                    0
Mean Motion                     0
Hazardous                       0
dtype: int64

In [9]:
df = df.dropna()

In [10]:
print('Number of features : ',df.shape[1])
print('Number of rows : ',df.shape[0])

Number of features :  34
Number of rows :  4687

In [11]:
df.Hazardous = df.Hazardous.astype(str)
df.Hazardous = df.Hazardous.replace({'true':1,'false':0})

In [12]:
X = df.drop('Hazardous',axis=1)
y = df.Hazardous

X = X.values.reshape((X.shape[0],-1))
y = y.values.reshape((y.shape[0],-1))
sc = StandardScaler()
X = sc.fit_transform(X)

In [13]:
X_train, X_eval,y_train, y_eval = train_test_split(X,y,random_state = 10,test_size=0.30)

In [14]:
print(X_train.shape, y_train.shape, X_eval.shape, y_eval.shape)

(3280, 33) (3280, 1) (1407, 33) (1407, 1)

In [15]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
prediction = lr.predict(X_eval)
print("classification_report",classification_report(prediction,y_eval))
print("accuracy_score : {} %".format(accuracy_score(prediction,y_eval)))

classification_report               precision    recall  f1-score   support

       False       0.97      0.97      0.97      1179
        True       0.84      0.86      0.85       228

    accuracy                           0.95      1407
   macro avg       0.91      0.91      0.91      1407
weighted avg       0.95      0.95      0.95      1407

accuracy_score : 0.9502487562189055 %

In [17]:
!pip install Lazypredict
from lazypredict.Supervised import LazyClassifier
clf = LazyClassifier(predictions=True)
models, predictions = clf.fit(X_train, X_eval, y_train, y_eval)
models

Requirement already satisfied: Lazypredict in /usr/local/lib/python3.6/dist-packages (0.2.7)
Requirement already satisfied: Click>=7.0 in /usr/local/lib/python3.6/dist-packages (from Lazypredict) (7.1.2)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)
100%|██████████| 30/30 [00:07<00:00,  3.99it/s]

                               Accuracy  ...  Time Taken
Model                                    ...
XGBClassifier                      1.00  ...        0.62
BaggingClassifier                  1.00  ...        0.23
AdaBoostClassifier                 1.00  ...        0.86
RandomForestClassifier             1.00  ...        0.70
LGBMClassifier                     1.00  ...        0.58
DecisionTreeClassifier             1.00  ...        0.08
ExtraTreesClassifier               0.98  ...        0.36
LinearSVC                          0.95  ...        0.18
CalibratedClassifierCV             0.95  ...        0.63
LogisticRegression                 0.95  ...        0.13
GaussianNB                         0.92  ...        0.04
Perceptron                         0.92  ...        0.06
ExtraTreeClassifier                0.95  ...        0.03
PassiveAggressiveClassifier        0.95  ...        0.06
SGDClassifier                      0.95  ...        0.08
SVC                                0.94  ...        0.39
LinearDiscriminantAnalysis         0.91  ...        0.12
QuadraticDiscriminantAnalysis      0.93  ...        0.06
LabelPropagation                   0.87  ...        0.73
LabelSpreading                     0.87  ...        0.93
KNeighborsClassifier               0.89  ...        0.27
RidgeClassifier                    0.90  ...        0.06
RidgeClassifierCV                  0.90  ...        0.08
NearestCentroid                    0.74  ...        0.06
BernoulliNB                        0.75  ...        0.04
DummyClassifier                    0.72  ...        0.03

[26 rows x 5 columns]

In [18]:
from sklearn.ensemble import AdaBoostClassifier

In [19]:
ada = AdaBoostClassifier()
ada.fit(X_train,y_train)
prediction = lr.predict(X_eval)
print("classification_report",classification_report(prediction,y_eval))
print("accuracy_score : {} %".format(accuracy_score(prediction,y_eval)))

classification_report               precision    recall  f1-score   support

       False       0.97      0.97      0.97      1179
        True       0.84      0.86      0.85       228

    accuracy                           0.95      1407
   macro avg       0.91      0.91      0.91      1407
weighted avg       0.95      0.95      0.95      1407

accuracy_score : 0.9502487562189055 %

In [20]:
import pickle
# save the model to disk
filename = 'model.sav'
pickle.dump(ada, open(filename, 'wb'))
 
# some time later...
 
'''
# load the model using these commands
model = pickle.load(open('model.sav', 'rb'))
pred = model.score(X_test, Y_test)
'''

"\n# load the model using these commands\nmodel = pickle.load(open('model.sav', 'rb'))\npred = model.score(X_test, Y_test)\n"